# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly. 
  
development:
  GOOGLE_APP_ID: "521218511066-m208ppirf66ugasqj3brkfcteg5dq2n3.apps.googleusercontent.com"
  GOOGLE_SECRET: "sRGreuI4E0lT04_84fB1W4Jy"
  secret_key_base: d4cc36016e2c3c46476667a3a0b53a0d2bda2c9bb1ab1358618c0fb0e00fa2bad2132f7473be5132eed77911e71a72bd4675334f07578a7cb46d85b0b23d2ab5

test:
  secret_key_base: d267d517dd5ff7022894432e45910860f84fc401ef3208b18ff1683b5c0b41d76d0e8c968cc70668bf70b462770b5d450f4ebc36286106ed65110c10d4db4857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_APP_ID: <%= ENV["GOOGLE_APP_ID"] %>
  GOOGLE_SECRET: <%= ENV["GOOGLE_SECRET"] %>

